export const VERIFIED_OFFICIAL_ROSTER = Object.freeze([
  {
    name: 'Rogie B. Quillope',
    position: 'Punong Barangay',
    contact: '09544153509',
    term: '2023 - 2026',
    termNumber: null,
    committee: null,
    order: 1,
  },
  {
    name: 'John Benedict B. Zarate',
    position: 'Barangay Kagawad',
    contact: null,
    term: '2023 - 2026',
    termNumber: '1st',
    committee: 'Health & Sanitation',
    order: 10,
  },
  {
    name: 'Armando M. Quillope Jr',
    position: 'Barangay Kagawad',
    contact: null,
    term: '2023 - 2026',
    termNumber: 'Last',
    committee: 'Appropriation',
    order: 11,
  },
  {
    name: 'Juan C. Fontalba',
    position: 'Barangay Kagawad',
    contact: null,
    term: '2023 - 2026',
    termNumber: '1st',
    committee: 'Infrastructure',
    order: 12,
  },
  {
    name: 'Jose A. Malinao',
    position: 'Barangay Kagawad',
    contact: null,
    term: '2023 - 2026',
    termNumber: '1st',
    committee: 'Environmental Protection',
    order: 13,
  },
  {
    name: 'Joel F. Ramos',
    position: 'Barangay Kagawad',
    contact: null,
    term: '2023 - 2026',
    termNumber: '2nd',
    committee: 'Agricultural',
    order: 14,
  },
  {
    name: 'Juanito R. Ramos',
    position: 'Barangay Kagawad',
    contact: null,
    term: '2023 - 2026',
    termNumber: '2nd',
    committee: 'Peace and Order',
    order: 15,
  },
  {
    name: 'Kerubin C. Ramos',
    position: 'Barangay Kagawad',
    contact: null,
    term: '2023 - 2026',
    termNumber: '1st',
    committee: 'Education',
    order: 16,
  },
  {
    name: 'Bhea Monique San Miguel',
    position: 'Barangay Secretary',
    contact: '09916982914',
    email: 'b.pag.asasj@gmail.com',
    term: '2023 - 2026',
    termNumber: null,
    committee: null,
    order: 20,
  },
  {
    name: 'Raymond Bautista',
    position: 'Chief Tanod',
    contact: '09336828737',
    term: '2023 - 2026',
    termNumber: null,
    committee: null,
    order: 21,
  },
  {
    name: 'Zenaida Velasco',
    position: 'BHW President',
    contact: '09074401517',
    term: '2023 - 2026',
    termNumber: null,
    committee: null,
    order: 22,
  },
]);
