import { Expo } from 'expo-server-sdk';
import PushReceipt from '../models/PushReceipt.js';
import User from '../models/User.js';

const expo = new Expo();
const INVALID_TOKEN_ERROR = 'DeviceNotRegistered';

const clearInvalidTokens = async (tokens) => {
  const uniqueTokens = [...new Set(tokens.filter(Boolean))];
  if (!uniqueTokens.length) return;

  await User.updateMany(
    { expoPushToken: { $in: uniqueTokens } },
    { $unset: { expoPushToken: 1 } }
  );
};

const saveReceiptTickets = async (ticketRecords) => {
  if (!ticketRecords.length) return;

  await PushReceipt.bulkWrite(ticketRecords.map(({ ticketId, expoPushToken }) => ({
    updateOne: {
      filter: { ticketId },
      update: {
        $set: {
          expoPushToken,
          status: 'pending',
          errorCode: null,
          checkedAt: null,
        },
      },
      upsert: true,
    },
  })));
};

/**
 * Queue push messages with Expo. `accepted` means Expo accepted the message
 * for processing; it does not claim that the device displayed the alert.
 */
export const sendPushNotifications = async (notifications) => {
  const invalidTokens = [];
  const validNotifications = notifications.filter((notification) => {
    if (Expo.isExpoPushToken(notification.pushToken)) return true;
    if (notification.pushToken) invalidTokens.push(notification.pushToken);
    return false;
  });

  if (invalidTokens.length) {
    await clearInvalidTokens(invalidTokens).catch((error) => {
      console.error('Unable to clear malformed Expo push tokens:', error.message);
    });
  }

  if (!validNotifications.length) {
    return { accepted: false, acceptedCount: 0, ticketIds: [] };
  }

  const messages = validNotifications.map((notification) => ({
    to: notification.pushToken,
    sound: 'default',
    priority: notification.priority,
    channelId: notification.channelId || 'default',
    title: notification.title,
    body: notification.body,
    data: notification.data || {},
  }));

  try {
    const chunks = expo.chunkPushNotifications(messages);
    const ticketRecords = [];
    const invalidRegisteredTokens = [];
    let acceptedCount = 0;
    let offset = 0;

    for (const chunk of chunks) {
      const chunkNotifications = validNotifications.slice(offset, offset + chunk.length);
      offset += chunk.length;
      const ticketChunk = await expo.sendPushNotificationsAsync(chunk);

      ticketChunk.forEach((ticket, index) => {
        const notification = chunkNotifications[index];
        if (ticket.status === 'ok' && ticket.id) {
          acceptedCount += 1;
          ticketRecords.push({ ticketId: ticket.id, expoPushToken: notification.pushToken });
          return;
        }

        if (ticket.details?.error === INVALID_TOKEN_ERROR) {
          invalidRegisteredTokens.push(notification.pushToken);
        }
        console.warn('Expo rejected a push notification:', ticket.message || 'Unknown ticket error');
      });
    }

    await Promise.all([
      saveReceiptTickets(ticketRecords),
      clearInvalidTokens(invalidRegisteredTokens),
    ]);

    return {
      accepted: acceptedCount > 0,
      acceptedCount,
      ticketIds: ticketRecords.map((record) => record.ticketId),
    };
  } catch (error) {
    console.error('Failed to queue push notification with Expo:', error.message);
    return { accepted: false, acceptedCount: 0, ticketIds: [] };
  }
};

export const sendPushNotification = async (pushToken, title, body, data = {}) => (
  sendPushNotifications([{ pushToken, title, body, data }])
);

/** Process Expo delivery receipts generated by previously accepted tickets. */
export const processPendingPushReceipts = async () => {
  const readyAt = new Date(Date.now() - 30 * 1000);
  const pending = await PushReceipt.find({
    status: 'pending',
    createdAt: { $lte: readyAt },
  }).sort({ createdAt: 1 }).limit(300).lean();

  if (!pending.length) return { checked: 0, invalidTokensCleared: 0 };

  const pendingByTicketId = new Map(pending.map((record) => [record.ticketId, record]));
  const receiptIds = pending.map((record) => record.ticketId);
  const invalidTokens = [];
  const updates = [];

  for (const receiptIdChunk of expo.chunkPushNotificationReceiptIds(receiptIds)) {
    const receipts = await expo.getPushNotificationReceiptsAsync(receiptIdChunk);
    Object.entries(receipts).forEach(([ticketId, receipt]) => {
      const pendingRecord = pendingByTicketId.get(ticketId);
      if (!pendingRecord) return;

      const isSuccess = receipt.status === 'ok';
      const errorCode = receipt.details?.error || null;
      if (!isSuccess && errorCode === INVALID_TOKEN_ERROR) {
        invalidTokens.push(pendingRecord.expoPushToken);
      }

      updates.push({
        updateOne: {
          filter: { ticketId, status: 'pending' },
          update: { $set: { status: isSuccess ? 'ok' : 'error', errorCode, checkedAt: new Date() } },
        },
      });
    });
  }

  if (updates.length) await PushReceipt.bulkWrite(updates);
  await clearInvalidTokens(invalidTokens);

  return { checked: updates.length, invalidTokensCleared: new Set(invalidTokens).size };
};
